---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-admin-sa
  namespace: CLUSTER_ID
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: CLUSTER_ID-cr
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: cluster-admin-sa
    namespace: CLUSTER_ID
---
apiVersion: batch/v1
kind: Job
metadata:
  # generateName: secret-copier-job- # Generic prefix
  name: secret-copier-job
  namespace: CLUSTER_ID
spec:
  template:
    spec:
      serviceAccountName: cluster-admin-sa
      containers:
      - name: copier
        image: quay.io/ocp-edge-qe/cli
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        command: ["/bin/bash", "-c"]
        args:
          - |
            oc -n openshift-config get secret pull-secret -ojson |jq 'del(.metadata.namespace, .metadata.uid, .metadata.resourceVersion, .metadata.creationTimestamp, .metadata.selfLink, .metadata.annotations, .metadata.ownerReferences) |.metadata.namespace = env.NAMESPACE |.metadata.name = (env.NAMESPACE + "-pull-secret")' |oc apply -f -
            oc -n openshift-config get secret bmc-secret  -ojson |jq 'del(.metadata.namespace, .metadata.uid, .metadata.resourceVersion, .metadata.creationTimestamp, .metadata.selfLink, .metadata.annotations, .metadata.ownerReferences) |.metadata.namespace = env.NAMESPACE |.metadata.name = (env.NAMESPACE + "-bmc-secret")'  |oc apply -f -
      restartPolicy: OnFailure
  backoffLimit: 3
