---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: ocp1m0w-a
  namespace: ocp1m0w-a
spec:
  holdInstallation: false
  baseDomain: qe.lab.redhat.com
  pullSecretRef:
    name: ocp1m0w-a-pull-secret
  clusterImageSetNameRef: "4.17"
  sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDm9hb6iTZJypEmzg4IZ767ze60UGhBWnjPXhovWVB7uKputdLzZhmlo36ifkXr/DTk8NGm47r6kXmz9NAF0pDHa5jX6yJFnhS4z5NY/mzsUX41gwiqBKYHgdp/KE1ylE8mbNon5ZpaaGvb876myjjPjPwWsD8hvXZirA5Q8TfDb/Pvgy1dhVH/uN05Ip1vVsp+bFGMPUJVWVUy/Eby5xW6OJv+FBOQq4nu6tslDZlHYXX2TSGrlW4x0i/oQMpKu/Y8ygAdjWqmAy6UBcho1nNWy15cp0jI5Fhjze171vSWZLAqJY+eFcL2kt/09RnY+MXyY/tIf+qNMyBE2Qltigah'
  clusterName: ocp1m0w-a
  clusterType: "SNO"
  cpuPartitioningMode: AllNodes
  templateRefs:
  - name: ai-cluster-templates-v1
    namespace: rhacm
  extraLabels:
    ManagedCluster:
      common: "true"
      du-profile: "latest"
      sites: ocp1m0w-a
  networkType: OVNKubernetes
  ignitionConfigOverride: '{"ignition":{"version":"3.2.0"},"storage":{"files":[{"path":"/etc/containers/policy.json","mode":420,"overwrite":true,"contents":{"source":"data:text/plain;charset=utf-8;base64,ewogICAgImRlZmF1bHQiOiBbCiAgICAgICAgewogICAgICAgICAgICAidHlwZSI6ICJpbnNlY3VyZUFjY2VwdEFueXRoaW5nIgogICAgICAgIH0KICAgIF0sCiAgICAidHJhbnNwb3J0cyI6CiAgICAgICAgewogICAgICAgICAgICAiZG9ja2VyLWRhZW1vbiI6CiAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgIiI6IFt7InR5cGUiOiJpbnNlY3VyZUFjY2VwdEFueXRoaW5nIn1dCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9"}}]}}'
  clusterNetwork:
    - cidr: "10.128.0.0/14"
      hostPrefix: 23
  machineNetwork:
    - cidr: 192.168.132.0/24
  serviceNetwork:
    - cidr: "172.30.0.0/16"
  nodes:
        - hostName: master-0
          role: master
          bmcAddress: redfish-virtualmedia+https://192.168.132.1:8000/redfish/v1/Systems/5028e620-34f3-4530-9931-36df87839c73
          bmcCredentialsName:
            name: ocp1m0w-a-bmc-secret
          bootMACAddress: 52:54:00:78:12:32
          automatedCleaningMode: disabled
          ironicInspect: ""
          ignitionConfigOverride: '{"ignition":{"version":"3.2.0"},"storage":{"disks":[{"device":"/dev/sda","partitions":[{"label":"var-lib-containers","sizeMiB":0,"startMiB":80000}],"wipeTable":false}],"filesystems":[{"device":"/dev/disk/by-partlabel/var-lib-containers","format":"xfs","mountOptions":["defaults","prjquota"],"path":"/var/lib/containers","wipeFilesystem":true}]},"systemd":{"units":[{"contents":"# Generated by Butane\n[Unit]\nRequires=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\nAfter=systemd-fsck@dev-disk-by\\x2dpartlabel-var\\x2dlib\\x2dcontainers.service\n\n[Mount]\nWhere=/var/lib/containers\nWhat=/dev/disk/by-partlabel/var-lib-containers\nType=xfs\nOptions=defaults,prjquota\n\n[Install]\nRequiredBy=local-fs.target","enabled":true,"name":"var-lib-containers.mount"}]}}'
          bootMode: UEFI
          templateRefs:
          - name: ai-node-templates-v1
            namespace: rhacm
          nodeNetwork:
            config:
              interfaces:
                - name: eth0
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    dhcp: true
                  ipv6:
                    enabled: false
            interfaces:
              - name: "eth0"
                macAddress: "52:54:00:78:12:32"
