apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  labels:
    app.kubernetes.io/instance: ocp-edge1-siteconfig
  name: ocp-edge1
  namespace: ocp-edge1
spec:
  clusterName: ocp-edge1
  baseDomain: lab.eng.tlv2.redhat.com
  clusterType: HighlyAvailable
  cpuArchitecture: x86_64
  clusterImageSetNameRef: "4.19"
  apiVIPs:
  - 10.46.57.10
  ingressVIPs:
  - 10.46.57.11
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: 10.46.57.0/24
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - cidr: 172.30.0.0/16
  cpuPartitioningMode: AllNodes
  extraLabels:
    ManagedCluster:
      common: 'true'
      du-profile: latest
      sites: ocp-edge1
  holdInstallation: false
  ignitionConfigOverride: '{"ignition":{"version":"3.2.0"},"storage":{"files":[{"path":"/etc/containers/policy.json","mode":420,"overwrite":true,"contents":{"source":"data:text/plain;charset=utf-8;base64,ewogICAgImRlZmF1bHQiOiBbCiAgICAgICAgewogICAgICAgICAgICAidHlwZSI6ICJpbnNlY3VyZUFjY2VwdEFueXRoaW5nIgogICAgICAgIH0KICAgIF0sCiAgICAidHJhbnNwb3J0cyI6CiAgICAgICAgewogICAgICAgICAgICAiZG9ja2VyLWRhZW1vbiI6CiAgICAgICAgICAgICAgICB7CiAgICAgICAgICAgICAgICAgICAgIiI6IFt7InR5cGUiOiJpbnNlY3VyZUFjY2VwdEFueXRoaW5nIn1dCiAgICAgICAgICAgICAgICB9CiAgICAgICAgfQp9"}}]}}'
  pullSecretRef:
    name: ocp-edge1-pull-secret
  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDm9hb6iTZJypEmzg4IZ767ze60UGhBWnjPXhovWVB7uKputdLzZhmlo36ifkXr/DTk8NGm47r6kXmz9NAF0pDHa5jX6yJFnhS4z5NY/mzsUX41gwiqBKYHgdp/KE1ylE8mbNon5ZpaaGvb876myjjPjPwWsD8hvXZirA5Q8TfDb/Pvgy1dhVH/uN05Ip1vVsp+bFGMPUJVWVUy/Eby5xW6OJv+FBOQq4nu6tslDZlHYXX2TSGrlW4x0i/oQMpKu/Y8ygAdjWqmAy6UBcho1nNWy15cp0jI5Fhjze171vSWZLAqJY+eFcL2kt/09RnY+MXyY/tIf+qNMyBE2Qltigah
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: rhacm
  nodes:
    - role: master
      hostName: master-0
      bmcAddress: redfish-virtualmedia+https://10.46.61.32/redfish/v1/Systems/1
      bmcCredentialsName:
        name: ocp-edge1-bmc-secret
      bootMACAddress: d4:f5:ef:40:75:09
      automatedCleaningMode: disabled
      bootMode: UEFI
      ironicInspect: ''
      nodeNetwork:
        config:
          interfaces:
            - ipv4:
                dhcp: true
                enabled: true
              ipv6:
                enabled: false
              name: eth0
              state: up
              type: ethernet
        interfaces:
          - macAddress: d4:f5:ef:40:75:09
            name: eth0
      templateRefs:
        - name: ai-node-templates-v1
          namespace: rhacm
    - role: master
      hostName: master-1
      bmcAddress: redfish-virtualmedia+https://10.46.61.29/redfish/v1/Systems/1
      bmcCredentialsName:
        name: ocp-edge1-bmc-secret
      bootMACAddress: d4:f5:ef:40:74:c0
      automatedCleaningMode: disabled
      bootMode: UEFI
      ironicInspect: ''
      nodeNetwork:
        config:
          interfaces:
            - ipv4:
                dhcp: true
                enabled: true
              ipv6:
                enabled: false
              name: eth0
              state: up
              type: ethernet
        interfaces:
          - macAddress: d4:f5:ef:40:74:c0
            name: eth0
      templateRefs:
        - name: ai-node-templates-v1
          namespace: rhacm
    - role: master
      hostName: master-2
      bmcAddress: redfish-virtualmedia+https://10.46.61.30/redfish/v1/Systems/1
      bmcCredentialsName:
        name: ocp-edge1-bmc-secret
      bootMACAddress: d4:f5:ef:40:82:00
      automatedCleaningMode: disabled
      bootMode: UEFI
      ironicInspect: ''
      nodeNetwork:
        config:
          interfaces:
            - ipv4:
                dhcp: true
                enabled: true
              ipv6:
                enabled: false
              name: eth0
              state: up
              type: ethernet
        interfaces:
          - macAddress: d4:f5:ef:40:82:00
            name: eth0
      templateRefs:
        - name: ai-node-templates-v1
          namespace: rhacm
