apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  annotations:
    bmac.agent-install.openshift.io/hostname: openshift-master-1.ocp-edge1.lab.eng.tlv2.redhat.com
    bmac.agent-install.openshift.io/role: master
    bmac.agent-install.openshift.io/cluster-reference: ocp-edge1/ocp-edge1
    bmac.agent-install.openshift.io/remove-agent-and-node-on-delete: true
  labels:
    infraenvs.agent-install.openshift.io: ocp-edge1
    cluster-name: ocp-edge1
  name: x240m5-12
spec:
  automatedCleaningMode: metadata
  architecture: x86_64
  bmc:
    address: ilo5-virtualmedia+https://10.46.61.29/redfish/v1/Systems/1    
    credentialsName: bmc-credentials
    disableCertificateVerification: true
  bootMACAddress: d4:f5:ef:40:74:c0
  online: true
  bootMode: UEFI